
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    File f;

    public signup() {
        initComponents();

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int width = d.width;
        int height = d.height;

        setSize(width, height);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jphoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 120, 30);

        jLabel2.setText("email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 120, 30);

        jLabel3.setText("phoneno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 120, 30);
        getContentPane().add(jusername);
        jusername.setBounds(240, 20, 110, 20);

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        getContentPane().add(jemail);
        jemail.setBounds(240, 50, 110, 20);
        getContentPane().add(jphone);
        jphone.setBounds(230, 90, 120, 20);

        jphoto.setText("jLabel4");
        getContentPane().add(jphoto);
        jphoto.setBounds(180, 140, 70, 40);

        jLabel5.setText("Image");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 120, 30);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 140, 73, 23);

        jButton2.setText("SIGNUP ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 200, 73, 23);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 270, 35, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        int ans = chooser.showOpenDialog(this);

        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
        }

        ImageIcon icon = new ImageIcon(f.getPath());
        Image resizedImage = icon.getImage().getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), SCALE_SMOOTH);
        jphoto.setIcon(new ImageIcon(resizedImage));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        myrequest obj = new myrequest();
        Thread t = new Thread(obj);
        t.start();

    }//GEN-LAST:event_jButton2ActionPerformed

    class myrequest implements Runnable {

        @Override
        public void run() {

            String username = jusername.getText();
            String email = jemail.getText();
            String phone = jphone.getText();

            try {
                HttpResponse<String> res = Unirest.post(server.ipaddress + "signup")
                        .queryString("username", username)
                        .queryString("email", email)
                        .queryString("phone", phone)
                        .field("photo", f)
                        .asString();

                if (res.getStatus() == 200) {
                    JOptionPane.showMessageDialog(rootPane, res.getBody());
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jphone;
    private javax.swing.JLabel jphoto;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
